"""
Django settings for lexenterprise project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-icm-+0%f4rcd%3db(2y#6jp7mo36+m#s_@%nrcb#b2u8f9593&'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = False

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['syciplexware.azurewebsites.net']

# Application definition

INSTALLED_APPS = [
    'fontawesomefree',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminapps.apps.AdminappsConfig',
    'associate_apps.apps.AssociateAppsConfig',
    'managing_apps.apps.ManagingAppsConfig',
    'supervising_apps.apps.SupervisingAppsConfig',
    'supportstaff.apps.SupportstaffConfig',
    'userprofile.apps.UserprofileConfig',
    'clientuserapps.apps.ClientuserappsConfig',
    'authentication.apps.AuthenticationConfig',
    'crispy_forms',
    'pdf_report.apps.PdfReportConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lexenterprise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lexenterprise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    "default": {
        'ENGINE': 'mssql',
        'NAME': 'LexEnprise',
        'USER': 'John',
        'PASSWORD': '640515',
        'HOST': '(LocalDb)\\MSSQLLocalDB',
        'PORT': '',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'lexenterprise',
#         'USER': 'postgres',
#         'PASSWORD':'640515john',
#         'HOST':'localhost',
#         'PORT':'5432',
#     }
#  }



# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'LexEnprise',
#         'USER': 'postgres',
#         'PASSWORD':'640515john',
#         'HOST':'DESKTOP-GH9PS35\\SQLEXPRESS',
#         'PORT':'1433',
#     }
#  }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         # 'NAME': 'lexenterprise',
#         'NAME': 'lexware',
#         'USER': 'jcampilla@lexwaredemo-psql-dbserver.postgres.database.azure.com',
#         'PASSWORD':'640515jscDb',
#         'HOST':'lexwaredemo-psql-dbserver.postgres.database.azure.com',
#         'PORT':'5432',
#     }
#  }

# application setting 'SCM_DO_BUILD_DURING_DEPLOYMENT'
#connection String
#dbname='{your_database}' user='dbname='{your_database}' user='lexsystem@pgsql-lexsystem' host='pgsql-lexsystem.postgres.database.azure.com' password='{your_password}' port='5432' sslmode='true'' host='pgsql-lexsystem.postgres.database.azure.com' password='{your_password}' port='5432' sslmode='true'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = (BASE_DIR/"asert/")
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_ROOT = (BASE_DIR/ 'media')
MEDIA_URL = '/media/'




LOGIN_REDIRECT_URL = 'sysadmin-home'

LOGIN_URL = 'user-login'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST_USER = "jclextrim@gmail.com"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_PASSWORD =""


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
