# Generated by Django 3.2.5 on 2022-04-28 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=15)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=15, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pf_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ofees_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ope_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_tag', models.CharField(blank=True, choices=[('UN', 'UNPAID'), ('PD', 'PAID'), ('PP', 'PARIALLY PAID'), ('CN', 'CANCELLED')], max_length=5, null=True)),
                ('DocPDFs', models.FileField(blank=True, upload_to='Bills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Accounts Receivable',
            },
        ),
        migrations.CreateModel(
            name='Action_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=15)),
                ('order_description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Case-Type Action Orders',
            },
        ),
        migrations.CreateModel(
            name='ActivityCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivityCode', models.CharField(blank=True, max_length=15)),
                ('Activity', models.CharField(max_length=250)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appearance',
            },
        ),
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apptype', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Types Of IP Applications',
            },
        ),
        migrations.CreateModel(
            name='BillingInstuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_description', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case Folders',
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Case Type',
            },
        ),
        migrations.CreateModel(
            name='Client_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Corporate', 'Corporate'), ('Individual', 'Individual')], max_length=20)),
                ('address', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('main_contact', models.CharField(max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('Big Entity', 'Big Entity'), ('Medium Entity', 'Medium Entity'), ('Small Entity', 'Small Entity')], max_length=20, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blacklisted', 'Blacklisted')], default='Active', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referredby', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Contact_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.client_data')),
            ],
            options={
                'verbose_name_plural': "Client's Contact Persons",
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Courts',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('local_rate', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Entities/Agencies',
            },
        ),
        migrations.CreateModel(
            name='FolderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Folder Type',
            },
        ),
        migrations.CreateModel(
            name='Lawyer_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=60)),
                ('access_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('remarks', models.CharField(max_length=200)),
                ('lawyerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Lawyers',
            },
        ),
        migrations.CreateModel(
            name='Matters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceno', models.CharField(blank=True, max_length=30)),
                ('clientrefno', models.CharField(blank=True, max_length=60)),
                ('matterno', models.CharField(blank=True, max_length=30)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('matter_title', models.TextField(null=True)),
                ('lawyers_involve', models.CharField(blank=True, max_length=60, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('appearance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.appearance')),
                ('apptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.apptype')),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.casetype')),
                ('filed_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.courts')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.casefolder')),
                ('handling_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.lawyer_data')),
                ('matter_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.contact_person')),
            ],
            options={
                'verbose_name_plural': 'Engagements/Accounts',
            },
        ),
        migrations.CreateModel(
            name='NatureOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Nature Of Business',
            },
        ),
        migrations.CreateModel(
            name='NatureOfCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Natures Of Cases',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('expense_detail', models.CharField(max_length=250)),
                ('expense_actual_amt', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('P', 'Paid'), ('C', 'Cancelled'), ('W', 'Waived')], max_length=15)),
                ('chargetoclient', models.BooleanField(default=False)),
                ('DocPDFs', models.FileField(blank=True, upload_to='Receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.matters')),
            ],
        ),
        migrations.CreateModel(
            name='TempBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('particulars', models.TextField(max_length=250)),
                ('spentinhrs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spentinmin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(max_length=60)),
                ('bill_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.activitycodes')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Temporary Service Rendered',
            },
        ),
        migrations.CreateModel(
            name='task_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField()),
                ('doc_type', models.CharField(choices=[('Outgoing', 'Outgoing'), ('Others', 'Others'), ('Incoming', 'Incoming')], max_length=20, null=True)),
                ('tran_type', models.CharField(choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True)),
                ('task', models.TextField()),
                ('spentinhrs', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('spentinmin', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
                ('preparedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.user_profile')),
                ('task_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.activitycodes')),
            ],
            options={
                'verbose_name_plural': 'Tasks/Activities',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=60)),
                ('casetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.casetype')),
            ],
            options={
                'verbose_name_plural': 'Stages Of The Case',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_for', models.CharField(choices=[('PF', 'for professional fees'), ('OFEE', 'For filing fees'), ('OPE', 'for expense fees'), ('Full', 'Full Payment'), ('Partial', 'Partial Payment')], max_length=10)),
                ('or_number', models.CharField(blank=True, max_length=15)),
                ('or_date', models.DateField(blank=True, null=True)),
                ('or_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bank_details', models.CharField(blank=True, max_length=150)),
                ('payment_reference', models.CharField(blank=True, max_length=30)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('Charge_details', models.CharField(blank=True, max_length=30)),
                ('Charge_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(blank=True, max_length=60)),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.accountsreceivable')),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='Order_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.client_data')),
                ('order_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.action_order')),
            ],
            options={
                'verbose_name_plural': "Client's Order",
            },
        ),
        migrations.CreateModel(
            name='OPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('ope_code', models.CharField(blank=True, max_length=10)),
                ('expense_details', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(max_length=60)),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.accountsreceivable')),
            ],
            options={
                'verbose_name_plural': 'Expenses Details',
            },
        ),
        migrations.CreateModel(
            name='OFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('fee_code', models.CharField(blank=True, max_length=10)),
                ('fee_particulars', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(max_length=60)),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.accountsreceivable')),
            ],
            options={
                'verbose_name_plural': 'Filing Fees (Expenses)',
            },
        ),
        migrations.AddField(
            model_name='matters',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.natureofcase'),
        ),
        migrations.AddField(
            model_name='matters',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.status'),
        ),
        migrations.CreateModel(
            name='IPTaskCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=15)),
                ('task_description', models.CharField(max_length=250)),
                ('ip_app_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.apptype')),
            ],
            options={
                'verbose_name_plural': 'Task Codes',
            },
        ),
        migrations.CreateModel(
            name='IP_Matters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo_examiner', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('REGISTERED', 'REGISTERED'), ('RENEWAL', 'RENEWAL'), ('PENDING', 'PENDING'), ('ABANDONED', 'ABANDONED'), ('TRANSFERRED', 'TRANSFERRED'), ('CANCELLED', 'CANCELLED')], max_length=20, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=30)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('ipc_appno', models.CharField(blank=True, max_length=25)),
                ('ipc_appdate', models.DateField(blank=True, null=True)),
                ('publication_reference', models.CharField(blank=True, max_length=30)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('priority_number', models.CharField(blank=True, max_length=25)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('priority_country_filing', models.CharField(blank=True, max_length=30)),
                ('pct_appno', models.CharField(blank=True, max_length=30)),
                ('pct_appdate', models.DateField(blank=True, null=True)),
                ('pct_publication', models.CharField(blank=True, max_length=30)),
                ('pct_pubdate', models.DateField(blank=True, null=True)),
                ('lng_interappln', models.CharField(blank=True, max_length=30)),
                ('lng_interpubln', models.CharField(blank=True, max_length=30)),
                ('reason_withdrawn', models.CharField(blank=True, max_length=200)),
                ('date_Of_PCTPriority', models.DateField(blank=True, null=True)),
                ('copyright_number', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'IP Matters',
            },
        ),
        migrations.CreateModel(
            name='FilingDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocDate', models.DateField(blank=True, null=True)),
                ('DocsPDF', models.FileField(blank=True, null=True, upload_to='Documents/%Y/%m/%D/')),
                ('Task_Detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.task_detail')),
            ],
        ),
        migrations.CreateModel(
            name='DueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DueCode', models.CharField(blank=True, max_length=20)),
                ('Description', models.CharField(blank=True, max_length=200)),
                ('basisofcompute', models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True)),
                ('fieldbsis', models.CharField(blank=True, choices=[('Document Date', 'Document Date'), ('Publication Date', 'PublicationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Registration Date', 'RegistrationDate'), ('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('Application Date', 'Application Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date')], max_length=30, null=True)),
                ('terms', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('apptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.apptype')),
                ('folder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.foldertype')),
            ],
        ),
        migrations.AddField(
            model_name='client_data',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.country'),
        ),
        migrations.AddField(
            model_name='client_data',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.natureofbusiness'),
        ),
        migrations.CreateModel(
            name='ClassOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.SmallIntegerField(null=True)),
                ('Goods_Descriptions', models.TextField(blank=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Classification Of Goods',
            },
        ),
        migrations.CreateModel(
            name='CaseMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('case_theory', models.TextField()),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Case Description/Theory',
            },
        ),
        migrations.AddField(
            model_name='casefolder',
            name='Supervisinglawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.lawyer_data'),
        ),
        migrations.AddField(
            model_name='casefolder',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.client_data'),
        ),
        migrations.AddField(
            model_name='casefolder',
            name='folder_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.foldertype'),
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField()),
                ('presented_by', models.CharField(max_length=150)),
                ('evidence_description', models.TextField(blank=True)),
                ('evidence_image', models.ImageField(blank=True, upload_to='')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Case Evidences',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(blank=True, max_length=10)),
                ('particulars', models.TextField(max_length=250)),
                ('spentinhrs', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('spentinmin', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.CharField(max_length=60)),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.accountsreceivable')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.lawyer_data')),
            ],
            options={
                'verbose_name_plural': 'Bill Details',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('Inventor', 'Inventor'), ('Individual', 'Individual'), ('Corporate', 'Corporate')], max_length=20, null=True)),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='AppDueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duecode', models.CharField(blank=True, max_length=20)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('particulars', models.CharField(max_length=250)),
                ('date_complied', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('assignto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Due Dates',
            },
        ),
        migrations.CreateModel(
            name='Alert_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_alert', models.DateField(blank=True, null=True)),
                ('message_alert', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('messageto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userprofile.user_profile')),
            ],
            options={
                'verbose_name_plural': 'Alert Messages',
            },
        ),
        migrations.AddField(
            model_name='activitycodes',
            name='foldertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.foldertype'),
        ),
        migrations.AddField(
            model_name='action_order',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.casetype'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.lawyer_data'),
        ),
        migrations.AddField(
            model_name='accountsreceivable',
            name='matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.matters'),
        ),
    ]
