# Generated by Django 4.0.4 on 2022-04-29 05:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0003_auto_20220428_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_data',
            name='IBPChapter',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='lawyer_data',
            name='IBPLifetimeNo',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='lawyer_data',
            name='IBPRollNo',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer_data',
            name='Specialization',
            field=models.CharField(default=datetime.datetime(2022, 4, 29, 5, 26, 48, 746569), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer_data',
            name='hourlyrate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Inventor', 'Inventor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Receipt Date', 'Document Receipt Date'), ('Registration Date', 'RegistrationDate'), ('Priority Date', 'Priority Date'), ('Document Date', 'Document Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Application Date', 'Application Date'), ('Publication Date', 'PublicationDate'), ('Renewal Date', 'Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Publication Date', 'PCT Publication Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'TRANSFERRED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('REGISTERED', 'REGISTERED'), ('RENEWAL', 'RENEWAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(choices=[('Outgoing', 'Outgoing'), ('Incoming', 'Incoming'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
    ]
