# Generated by Django 4.0.4 on 2022-05-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0007_alter_appduedate_assignto_alter_applicant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IPOExaminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MailsIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receipt', models.DateField()),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('mailing_date', models.DateField(blank=True)),
                ('mail_type', models.CharField(blank=True, choices=[('Email', 'Email'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50)),
                ('particulars', models.CharField(max_length=200)),
                ('attentionto', models.ManyToManyField(blank=True, to='adminapps.lawyer_data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.client_data')),
                ('documentcode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.documentcode')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.ipoexaminer')),
            ],
            options={
                'verbose_name_plural': 'Mails Inward',
                'ordering': ['date_receipt'],
            },
        ),
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('Corporate', 'Corporate'), ('Inventor', 'Inventor'), ('Individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Years', 'In Years'), ('In Months', 'In Months'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Filing Date', 'PCT Filing Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date'), ('Renewal Date', 'Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Date', 'Document Date'), ('Application Date', 'Application Date'), ('Priority Date', 'Priority Date'), ('Publication Date', 'PublicationDate'), ('PCT Publication Date', 'PCT Publication Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('RENEWAL', 'RENEWAL'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('TRANSFERRED', 'TRANSFERRED'), ('PENDING', 'PENDING'), ('REGISTERED', 'REGISTERED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(choices=[('Outgoing', 'Outgoing'), ('Incoming', 'Incoming'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MailsIn_Matters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapps.mailsin')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapps.matters')),
            ],
            options={
                'verbose_name_plural': 'Mails In Matters',
            },
        ),
    ]
