# Generated by Django 4.0.4 on 2022-05-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0009_alter_applicant_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Inventor', 'Inventor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Publication Date', 'PublicationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Renewal Date', 'Renewal Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Date', 'Document Date'), ('Application Date', 'Application Date'), ('Priority Date', 'Priority Date'), ('Registration Date', 'RegistrationDate'), ('Document Receipt Date', 'Document Receipt Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('CANCELLED', 'CANCELLED'), ('REGISTERED', 'REGISTERED'), ('PENDING', 'PENDING'), ('TRANSFERRED', 'TRANSFERRED'), ('ABANDONED', 'ABANDONED'), ('RENEWAL', 'RENEWAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='documentcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.documentcode'),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Email', 'Email'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Others', 'Others'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
    ]
