# Generated by Django 4.0.4 on 2022-05-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0010_alter_applicant_category_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='doc_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.ipoexaminer'),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Mail', 'Mail'), ('Email', 'Email')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='mailing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Registration Date', 'RegistrationDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Application Date', 'Application Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Document Date', 'Document Date'), ('Renewal Date', 'Renewal Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Publication Date', 'PublicationDate'), ('Priority Date', 'Priority Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('ABANDONED', 'ABANDONED'), ('PENDING', 'PENDING'), ('RENEWAL', 'RENEWAL'), ('CANCELLED', 'CANCELLED'), ('TRANSFERRED', 'TRANSFERRED'), ('REGISTERED', 'REGISTERED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Mail', 'Mail'), ('Email', 'Email')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Others', 'Others')], max_length=20, null=True),
        ),
    ]
