# Generated by Django 4.0.4 on 2022-05-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('adminapps', '0012_alter_applicant_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('Inventor', 'Inventor'), ('Corporate', 'Corporate'), ('Individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Months', 'In Months'), ('In Years', 'In Years'), ('In Days', 'In Days')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Priority Date', 'Priority Date'), ('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Renewal Date', 'Renewal Date'), ('Document Date', 'Document Date'), ('Registration Date', 'RegistrationDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'TRANSFERRED'), ('RENEWAL', 'RENEWAL'), ('CANCELLED', 'CANCELLED'), ('REGISTERED', 'REGISTERED'), ('PENDING', 'PENDING'), ('ABANDONED', 'ABANDONED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Mail', 'Mail'), ('Email', 'Email')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(choices=[('Outgoing', 'Outgoing'), ('Others', 'Others'), ('Incoming', 'Incoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Mail', 'Mail'), ('Email', 'Email')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='preparedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.user_profile'),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
    ]
