# Generated by Django 4.0.4 on 2022-05-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0015_alter_applicant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbills',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('P', 'Proforma'), ('B', 'Billed'), ('C', 'Cancelled'), ('W', 'Waived')], max_length=15),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='category',
            field=models.CharField(choices=[('Inventor', 'Inventor'), ('Corporate', 'Corporate'), ('Individual', 'Individual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Priority Date', 'Priority Date'), ('Application Date', 'Application Date'), ('Registration Date', 'RegistrationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('Renewal Date', 'Renewal Date'), ('Publication Date', 'PublicationDate'), ('Document Date', 'Document Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Receipt Date', 'Document Receipt Date'), ('PCT Filing Date', 'PCT Filing Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'TRANSFERRED'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('RENEWAL', 'RENEWAL'), ('REGISTERED', 'REGISTERED'), ('PENDING', 'PENDING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Mail', 'Mail'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Others', 'Others'), ('Outgoing', 'Outgoing'), ('Incoming', 'Incoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Mail', 'Mail'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tempexpenses',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('P', 'Proforma'), ('B', 'Billed'), ('C', 'Cancelled'), ('W', 'Waived')], max_length=15),
        ),
        migrations.CreateModel(
            name='TempFilingFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('expense_detail', models.CharField(max_length=250)),
                ('expense_actual_amt', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(blank=True, choices=[('O', 'Open'), ('P', 'Proforma'), ('B', 'Billed'), ('C', 'Cancelled'), ('W', 'Waived')], max_length=15)),
                ('chargetoclient', models.BooleanField(blank=True, default=False)),
                ('DocPDFs', models.FileField(blank=True, upload_to='Receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.lawyer_data')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='adminapps.matters')),
            ],
        ),
    ]
