# Generated by Django 4.0.4 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0031_remove_tempexpenses_bill_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdocs',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Document Receipt Date', 'Document Receipt Date'), ('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('Priority Date', 'Priority Date'), ('Registration Date', 'RegistrationDate'), ('PCT Publication Date', 'PCT Publication Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Document Date', 'Document Date'), ('OA Mailing Date', 'OA Mailing Date'), ('Renewal Date', 'Renewal Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('RENEWAL', 'RENEWAL'), ('TRANSFERRED', 'TRANSFERRED'), ('REGISTERED', 'REGISTERED'), ('ABANDONED', 'ABANDONED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Billable', 'Billable'), ('Non-Billable', 'Non-Billable')], max_length=15, null=True),
        ),
    ]
