# Generated by Django 4.0.5 on 2022-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0039_natureofcase_casetype_alter_duecode_basisofcompute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='category',
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casematter',
            name='case_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casematter',
            name='case_theory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classofgoods',
            name='Goods_Descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classofgoods',
            name='classes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Publication Date', 'PublicationDate'), ('PCT Filing Date', 'PCT Filing Date'), ('Priority Date', 'Priority Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Application Date', 'Application Date'), ('Renewal Date', 'Renewal Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Registration Date', 'RegistrationDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Document Date', 'Document Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('ABANDONED', 'ABANDONED'), ('RENEWAL', 'RENEWAL'), ('REGISTERED', 'REGISTERED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True),
        ),
    ]
