# Generated by Django 4.0.5 on 2022-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0041_alter_duecode_basisofcompute_alter_duecode_fieldbsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awaitingdocs',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Waiting'), ('R', 'Received'), ('C', 'Cancelled')], max_length=15),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Renewal Date', 'Renewal Date'), ('Priority Date', 'Priority Date'), ('Document Date', 'Document Date'), ('Document Receipt Date', 'Document Receipt Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Publication Date', 'PublicationDate'), ('Application Date', 'Application Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Registration Date', 'RegistrationDate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('UNREAD', 'UNREAD'), ('READ', 'READ')], default='UNREAD', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('RENEWAL', 'RENEWAL'), ('ABANDONED', 'ABANDONED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('REGISTERED', 'REGISTERED'), ('TRANSFERRED', 'TRANSFERRED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Billed', 'Billed'), ('Unbilled', 'Unbilled')], default='Unbilled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Incoming', 'Incoming'), ('Others', 'Others'), ('Outgoing', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Personal', 'Personal'), ('Mail', 'Mail')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
    ]
