# Generated by Django 4.0.5 on 2022-07-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0042_awaitingdocs_status_alter_duecode_basisofcompute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appduedate',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Years', 'In Years'), ('In Months', 'In Months')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('Application Date', 'Application Date'), ('Document Date', 'Document Date'), ('Renewal Date', 'Renewal Date'), ('Registration Date', 'RegistrationDate'), ('Priority Date', 'Priority Date'), ('OA Mailing Date', 'OA Mailing Date'), ('PCT Filing Date', 'PCT Filing Date'), ('PCT Publication Date', 'PCT Publication Date'), ('Publication Date', 'PublicationDate'), ('Document Receipt Date', 'Document Receipt Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'TRANSFERRED'), ('CANCELLED', 'CANCELLED'), ('RENEWAL', 'RENEWAL'), ('ABANDONED', 'ABANDONED'), ('PENDING', 'PENDING'), ('REGISTERED', 'REGISTERED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailsin',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Email', 'Email'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='billstatus',
            field=models.CharField(blank=True, choices=[('Unbilled', 'Unbilled'), ('Billed', 'Billed')], default='Unbilled', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Outgoing', 'Outgoing'), ('Others', 'Others'), ('Incoming', 'Incoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='mail_type',
            field=models.CharField(blank=True, choices=[('Mail', 'Mail'), ('Email', 'Email'), ('Personal', 'Personal')], max_length=15, null=True),
        ),
    ]
