# Generated by Django 4.0.5 on 2022-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapps', '0044_appduedate_updatedby_alter_duecode_basisofcompute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='createdby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='updatedby',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='basisofcompute',
            field=models.CharField(blank=True, choices=[('In Days', 'In Days'), ('In Months', 'In Months'), ('In Years', 'In Years')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='duecode',
            name='fieldbsis',
            field=models.CharField(blank=True, choices=[('PCT Publication Date', 'PCT Publication Date'), ('Document Receipt Date', 'Document Receipt Date'), ('Registration Date', 'RegistrationDate'), ('Renewal Date', 'Renewal Date'), ('Publication Date', 'PublicationDate'), ('OA Mailing Date', 'OA Mailing Date'), ('Application Date', 'Application Date'), ('PCT Filing Date', 'PCT Filing Date'), ('Priority Date', 'Priority Date'), ('Document Date', 'Document Date')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ip_matters',
            name='status',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'TRANSFERRED'), ('CANCELLED', 'CANCELLED'), ('ABANDONED', 'ABANDONED'), ('PENDING', 'PENDING'), ('REGISTERED', 'REGISTERED'), ('RENEWAL', 'RENEWAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='tran_type',
            field=models.CharField(blank=True, choices=[('Non-Billable', 'Non-Billable'), ('Billable', 'Billable')], max_length=15, null=True),
        ),
    ]
