# Generated by Django 4.0.4 on 2022-05-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='supporto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
