# Generated by Django 4.0.4 on 2022-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_profile_supporto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='access_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
