# Generated by Django 4.0.5 on 2022-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_user_profile_name_alter_user_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
