# Generated by Django 4.0.5 on 2023-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_user_profile_date_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='rank',
            field=models.CharField(choices=[('MANAGING PARTNER', 'MANAGING PARTNER'), ('PARTNER', 'PARTNER'), ('ASSOCIATES', 'ASSOCIATES'), ('SECRETARY', 'SECRETARY'), ('PARALEGAL', 'PARALEGAL'), ('MIS STAFF', 'MIS STAFF'), ('SYSTEM ADMIN', 'SYSTEM ADMIN'), ('ACCOUNTING STAFF', 'ACCOUNTING STAFF'), ('DATA ENCODER', 'DATA ENCODER'), ('FRONTEND DEVELOPER', 'FRONTEND DEVELOPER'), ('BACKEND DEVELOPER', 'BACKEND DEVELOPER'), ('SYSTEM DEVELOPER', 'SYSTEM DEVELOPER'), ('CLIENT', 'CLIENT')], max_length=30, null=True),
        ),
    ]
