# Generated by Django 3.2.5 on 2022-04-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapps', '0002_auto_20220428_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationtype', models.CharField(choices=[('INV', 'Invention'), ('UM', 'Utility Model'), ('DS', 'Design'), ('TM', 'Trademark'), ('PCT', 'PCT')], max_length=10)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LawyersCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofcases', models.PositiveIntegerField()),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapps.lawyer_data')),
            ],
        ),
    ]
