# Generated by Django 4.0.5 on 2022-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSummaryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('no_of_matters', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
