# Generated by Django 4.0.5 on 2022-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_apps', '0002_clientsummarycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTypeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetype', models.CharField(max_length=60)),
                ('no_of_matters', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lawyer', models.CharField(max_length=5)),
                ('no_of_matters', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
