# Generated by Django 4.0.5 on 2022-06-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing_apps', '0003_casetypesummary_lawyersummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTypeSummary_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetype', models.CharField(max_length=60)),
                ('no_of_matters', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
